name: AgosecKeyboard
options:
  bundleIdPrefix: io.agosec
  deploymentTarget:
    iOS: "16.0"
  groupSortPosition: top
  useBaseInternationalization: false
settings:
  base:
    SWIFT_VERSION: "5.9"
    ALWAYS_SEARCH_USER_PATHS: NO
    EXCLUDED_ARCHS[sdk=iphonesimulator*]: "x86_64"
    ONLY_ACTIVE_ARCH: YES
packages:
  SharedCore:
    path: Packages/SharedCore
  Networking:
    path: Packages/Networking
  OCR:
    path: Packages/OCR
  UIComponents:
    path: Packages/UIComponents
  KeyboardKit:
    url: https://github.com/KeyboardKit/KeyboardKit.git
    from: 10.0.0
  SymSpellSwift:
    url: https://github.com/gdetari/SymSpellSwift.git
    from: 0.1.4
  LicenseKit:
    url: https://github.com/LicenseKit/LicenseKit.git
    from: 2.1.3
targets:
  AgosecApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - AgosecApp
    info:
      path: AgosecApp/Info.plist
      properties:
        CFBundleDisplayName: Agosec
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        UIRequiredDeviceCapabilities:
          - armv7
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - agosec
        NSPhotoLibraryUsageDescription: "Agosec needs access to your photos to import screenshots for AI context awareness."
        BACKEND_BASE_URL: "https://api.agosec.com"
        MOCK_BACKEND_ENABLED: true
        SUBSCRIPTION_PRODUCT_ID: "io.agosec.keyboard.pro"
        ENV: "prod"
        FEATURE_AGENT_PHOTOS_ENABLED: true
        MAX_SCREENSHOTS_PER_IMPORT: 5
        MAX_CONTEXT_CHARS: 20000
        MAX_TURNS_SENT: 12
        KEYBOARD_EXTENSION_BUNDLE_ID: "io.agosec.keyboard.app.extension"
        APP_GROUP_ID: "group.io.agosec.keyboard"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: io.agosec.keyboard.app
      PRODUCT_NAME: AgosecApp
      CODE_SIGN_ENTITLEMENTS: AgosecApp/AgosecApp.entitlements
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: "V9CU7HF844"
      INFOPLIST_FILE: AgosecApp/Info.plist
      SWIFT_VERSION: "5.9"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: "YES"
      ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: "YES"
      LD_RUNPATH_SEARCH_PATHS:
        - "$(inherited)"
        - "@executable_path/Frameworks"
        - "@loader_path/Frameworks"
    dependencies:
      - package: SharedCore
      - package: Networking
      - package: OCR
      - package: UIComponents
      - package: KeyboardKit
      - sdk: StoreKit.framework
      - sdk: PhotosUI.framework
      - target: AgosecKeyboardExtension
        embed: true
    scheme:
      testTargets:
        - AgosecAppTests
  AgosecKeyboardExtension:
    type: app-extension
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - AgosecKeyboardExtension
      - AgosecKeyboardExtension/Keyboard/KeyboardNotifications.swift
    resources:
      - AgosecKeyboardExtension/Resources/Assets.xcassets
      - AgosecKeyboardExtension/Resources/Autocomplete
    info:
      path: AgosecKeyboardExtension/Info.plist
      properties:
        CFBundleDisplayName: Agosec Keyboard
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        NSExtension:
          NSExtensionAttributes:
            IsASCIICapable: false
            PrefersRightToLeft: false
            PrimaryLanguage: en-US
            RequestsOpenAccess: true
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).KeyboardViewController
          NSExtensionPointIdentifier: com.apple.keyboard-service
        BACKEND_BASE_URL: "https://api.agosec.com"
        MOCK_BACKEND_ENABLED: true
        SUBSCRIPTION_PRODUCT_ID: "io.agosec.keyboard.pro"
        ENV: "prod"
        FEATURE_AGENT_PHOTOS_ENABLED: true
        MAX_SCREENSHOTS_PER_IMPORT: 5
        MAX_CONTEXT_CHARS: 20000
        MAX_TURNS_SENT: 12
        APP_GROUP_ID: "group.io.agosec.keyboard"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: io.agosec.keyboard.app.extension
      PRODUCT_NAME: AgosecKeyboardExtension
      CODE_SIGN_ENTITLEMENTS: AgosecKeyboardExtension/AgosecKeyboardExtension.entitlements
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: "V9CU7HF844"
      INFOPLIST_FILE: AgosecKeyboardExtension/Info.plist
      SWIFT_VERSION: "5.9"
      ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: "YES"
      LD_RUNPATH_SEARCH_PATHS:
        - "$(inherited)"
        - "@executable_path/Frameworks"
        - "@loader_path/Frameworks"
    dependencies:
      - package: SharedCore
      - package: Networking
      - package: OCR
      - package: UIComponents
      - package: KeyboardKit
      - package: SymSpellSwift
      - package: LicenseKit
      - sdk: Vision.framework
      - sdk: PhotosUI.framework
      - sdk: StoreKit.framework
    postBuildScripts:
      - name: Embed Keyboard Frameworks
        shell: /bin/sh
        script: |
          set -euo pipefail

          frameworks_dir="${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}"
          mkdir -p "$frameworks_dir"

          for framework in KeyboardKit LicenseKit; do
            source_framework="${BUILT_PRODUCTS_DIR}/${framework}.framework"
            if [ ! -d "$source_framework" ]; then
              echo "error: Expected framework not found: $source_framework"
              exit 1
            fi

            rm -rf "${frameworks_dir}/${framework}.framework"
            ditto "$source_framework" "${frameworks_dir}/${framework}.framework"
          done
  AgosecAppTests:
    type: bundle.unit-test
    platform: iOS
    sources: AgosecAppTests
    settings:
      SWIFT_VERSION: "5.9"
    dependencies:
      - target: AgosecApp
fileGroups:
  - Packages
  - README.md
